from pathlib import Path

def edit(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if s.count(old)<count: raise SystemExit(f"missing block in {path}: {old[:120]!r}")
    p.write_text(s.replace(old,new,count))

edit('scripts/cafe.gd','const Player = preload("res://scripts/fps_player.gd")\nconst Service = preload("res://scripts/cafe_service.gd")','const Player = preload("res://scripts/fps_player.gd")\nconst Service = preload("res://scripts/cafe_service.gd")\nconst Annex = preload("res://scripts/cafe_annex.gd")')
edit('scripts/cafe.gd','var evening: Node3D\nvar laboratory: Node3D','var evening: Node3D\nvar annex: Node3D\nvar laboratory: Node3D')
edit('scripts/cafe.gd','''\tlaboratory = preload("res://scripts/clone_laboratory.gd").new()\n\tadd_child(laboratory)\n\tlaboratory.setup(self)\n\tevening=preload("res://scripts/staff_evening.gd").new()\n\tadd_child(evening)\n\tevening.setup(self)''','''\tlaboratory = preload("res://scripts/clone_laboratory.gd").new()\n\tadd_child(laboratory)\n\tAnnex.place_lab(laboratory)\n\tlaboratory.setup(self)\n\tevening=preload("res://scripts/staff_evening.gd").new()\n\tadd_child(evening)\n\tevening.setup(self)\n\tannex=Annex.new()\n\tadd_child(annex)\n\tannex.setup(self)''')
edit('scripts/cafe.gd','''\tfor x in [-11.8, 17.8]:\n\t\tProps.solid_box(self, Vector3(0.18, 4.7, 18.2), Vector3(x, 2.3, 1.5), Color("2e5355"))''','''\tProps.solid_box(self, Vector3(0.18, 4.7, 18.2), Vector3(17.8, 2.3, 1.5), Color("2e5355"))\n\tAnnex.build_shell(self)''')

edit('scripts/clone_laboratory.gd','var root:=Node3D.new(); add_child(root); root.position=upgrade_position(item); upgrade_nodes[item]=root','var root:=Node3D.new(); add_child(root); root.position=upgrade_local_position(item); upgrade_nodes[item]=root')
edit('scripts/clone_laboratory.gd','''func upgrade_position(item: String) -> Vector3:\n\treturn {"lab_power":Vector3(-1.40,1.25,8.5),"lab_power_2":Vector3(1.42,1.25,8.5),"lab_valve":Vector3(-0.65,1.25,8.6),"lab_damper":Vector3(0.55,1.25,8.6)}[item]''','''func upgrade_local_position(item: String) -> Vector3:\n\treturn {"lab_power":Vector3(-1.40,1.25,8.5),"lab_power_2":Vector3(1.42,1.25,8.5),"lab_valve":Vector3(-0.65,1.25,8.6),"lab_damper":Vector3(0.55,1.25,8.6)}[item]\n\nfunc upgrade_position(item: String) -> Vector3:\n\treturn to_global(upgrade_local_position(item))\n\nfunc operator_position() -> Vector3:\n\treturn to_global(Vector3(0,0.02,7.0))''')
edit('scripts/clone_laboratory.gd','''func inside(position: Vector3) -> bool:\n\treturn absf(position.x)<2.9 and position.z>6.5 and position.distance_to(BUTTON)<3.6\n\nfunc target(camera: Camera3D, peer: int) -> Dictionary:\n\tif not inside(camera.global_position): return {}\n\tif state.phase=="idle":\n\t\tfor side in [-1,1]:\n\t\t\tif game.shop.near_ray(camera,Vector3(side*0.42,1.12,7.76),0.15): return {"action":"lab_select","direction":side,"revision":state.revision,"hint":"(E) Выбрать клона / создание нового"}\n\telif int(state.owner)==peer and state.phase not in ["done","failed"] and game.shop.near_ray(camera,Vector3(-1.48,1.09,7.88),0.18):\n\t\treturn {"action":"lab_restart","revision":state.revision,"hint":"(E) Прервать · ингредиенты потрачены"}\n\tif not game.shop.near_ray(camera,Vector3(0,1.5,8) if state.phase!="idle" else BUTTON,1.3 if state.phase!="idle" else 0.25): return {}''','''func inside(position: Vector3) -> bool:\n\tvar local := to_local(position)\n\treturn absf(local.x)<2.9 and local.z>6.5 and local.distance_to(BUTTON)<3.6\n\nfunc target(camera: Camera3D, peer: int) -> Dictionary:\n\tif not inside(camera.global_position): return {}\n\tif state.phase=="idle":\n\t\tfor side in [-1,1]:\n\t\t\tif game.shop.near_ray(camera,to_global(Vector3(side*0.42,1.12,7.76)),0.15): return {"action":"lab_select","direction":side,"revision":state.revision,"hint":"(E) Выбрать клона / создание нового"}\n\telif int(state.owner)==peer and state.phase not in ["done","failed"] and game.shop.near_ray(camera,to_global(Vector3(-1.48,1.09,7.88)),0.18):\n\t\treturn {"action":"lab_restart","revision":state.revision,"hint":"(E) Прервать · ингредиенты потрачены"}\n\tvar interaction_point := to_global(Vector3(0,1.5,8)) if state.phase!="idle" else to_global(BUTTON)\n\tif not game.shop.near_ray(camera,interaction_point,1.3 if state.phase!="idle" else 0.25): return {}''')

edit('scripts/cafe_shop.gd','const Props = preload("res://scripts/props.gd")','const Props = preload("res://scripts/props.gd")\nconst Annex = preload("res://scripts/cafe_annex.gd")')
edit('scripts/cafe_shop.gd','func lab_position(index: int) -> Vector3: return Vector3(-0.85+index*0.85,1.05,8.6)','func lab_position(index: int) -> Vector3: return Annex.lab_world(Vector3(-0.85+index*0.85,1.05,8.6))\nfunc garland_reel_position() -> Vector3: return Annex.lab_world(Vector3(1.48,1.1,8.15))')
edit('scripts/cafe_shop.gd','if spec.kind == "garland": return Vector3(1.48,1.1,8.15)','if spec.kind == "garland": return garland_reel_position()')
edit('scripts/cafe_shop.gd','if near_ray(camera,Vector3(1.48,1.1,8.15),0.3): return {"action":"garland_put" if p.garland_builder==peer else "garland_take","hint":"(E) Положить катушку" if p.garland_builder==peer else "(E) Взять гирлянду"}','if near_ray(camera,garland_reel_position(),0.3): return {"action":"garland_put" if p.garland_builder==peer else "garland_take","hint":"(E) Положить катушку" if p.garland_builder==peer else "(E) Взять гирлянду"}')
