extends RefCounted
const M = preload("res://scripts/team_cooking_model.gd")
var commands: Array = []
func step(command := {}, count := 1) -> void:
	for i in range(count): commands.append(command.duplicate(true))
func move(point: Vector2, elevation: float, count := 60) -> void:
	step({"target": [point.x, point.y], "height": elevation}, count)
func meat_role() -> void:
	step({"grab": "steak"})
	move(M.GRILL, 0.3)
	step({"drop": true})
	step({}, 370)
	step({"grab": "spatula"})
	move(M.GRILL, 0.3)
	step({"use": true})
	move(Vector2(0, 0.02), 0.3)
	step({"drop": true})
	step({"grab": "salt"})
	move(M.GRILL, 0.6)
	step({"use": true}, 40)
	move(Vector2(0, -0.48), 0.5)
	step({"drop": true})
	step({}, 220)
	step({"grab": "steak"})
	move(M.PLATE, 0.3)
	step({"drop": true})

func pasta_role() -> void:
	step({"grab": "water"})
	move(M.STOVE, 0.6)
	step({"use": true}, 160)
	move(Vector2(2.3, 0.45), 0.5)
	step({"drop": true})
	step({"grab": "pasta_bag"})
	move(M.STOVE, 0.6)
	step({"use": true}, 130)
	move(Vector2(2.25, -0.55), 0.5)
	step({"drop": true})
	step({}, 180)
	step({"grab": "pasta_spatula"})
	move(M.STOVE, 0.3)
	step({"use": true}, 130)
	move(Vector2(0, 0.02), 0.3)
	step({"drop": true})
	step({}, 720)
	step({"grab": "pot"})
	move(M.PASTA_PLATE, 0.5)
	step({"use": true}, 60)
	move(M.STOVE, 0.4)
	step({"drop": true})
	step({"grab": "pasta_salt_tool"})
	move(M.PASTA_PLATE, 0.6)
	step({"use": true}, 40)
	move(Vector2(0, -0.48), 0.4)
	step({"drop": true})

