extends SceneTree
const Model = preload("res://scripts/cooking_model.gd")
func _initialize() -> void: run.call_deferred()
func run() -> void:
	var m = Model.new()
	m.reset("sausage")
	var expected_shelf_center: Vector2 = m.Layout.SHELF_HOME + m.Layout.shelf_forward() * (m.Layout.SHELF_HALF.y * 0.5)
	assert(m.Layout.shelf_center().distance_to(expected_shelf_center) < 0.0001, "product shelf should be pulled forward by one quarter depth")
	assert(is_equal_approx(m.Layout.SHELF_YAW, PI / 4.0), "product shelf should face the cook at 45 degrees")
	for point in [m.jug, m.tomato, m.potatoes[0].potato, m.potatoes[1].potato, m.potatoes[2].potato, m.sausages[0].sausage, m.sausages[1].sausage, m.sausages[2].sausage]:
		assert(m.Layout.shelf_contains(point), "initial stock should remain on the rotated shelf")
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2.ZERO)
	m.put_down()
	m.pick_up("sausage_0")
	m.move_item("sausage", Vector2.ZERO)
	m.put_down()
	assert(m.sausage_state == "plate_2", "food should attach to moved plate")
	m.pick_up("plate_2")
	m.move_item("plate_2", m.Layout.TRAY)
	m.put_down()
	assert(m.served_index("sausage") == 0)
	assert(m.served_in_dish("sausage"))
	var copy = Model.new()
	copy.restore(m.snapshot())
	assert(copy.served_in_dish("sausage"))
	m.reset("wine")
	m._deliver(m.Layout.TRAY, 225, 2.0)
	assert(m.served_wine() == 225)
	assert(m.quality().grade == "A")
	assert(m.spilled() == 0)
	m.reset("wine")
	m.pick_up("cup")
	m.move_item("cup", m.Layout.TRAY)
	m.put_down()
	m.filled = 225
	assert(m.quality().grade == "S")
	m._deliver(m.cup, 100, 2.0)
	assert(m.filled == 300 and m.tray_wine == 25)
	assert(m.spilled() == 0, "cup overflow on tray is served, not lost")
	m.reset("sausage")
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2.ZERO)
	m.put_down()
	m.pick_up("sausage_0")
	m.move_item("sausage", Vector2(0.1, 0.0))
	m.put_down()
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2(0.5, 0.0))
	m.lift_held(0.2)
	m.step(0.1, false, true, false)
	assert(m.sausage.distance_to(Vector2(0.6, 0)) < 0.001)
	assert(m.sausage_slip == 0)
	for i in range(10): m.step(0.1, true, false, false)
	assert(not m.sausage_state.begins_with("plate_"), "tilting plate releases food")
	var game = load("res://scenes/cafe.tscn").instantiate()
	root.add_child(game)
	await process_frame
	game.service.open_for_business = false
	for i in range(5): await process_frame
	var station = game.service.by_id(1)
	var zone_size: Vector2 = station.training_zone_max() - station.training_zone_min()
	assert(is_equal_approx(zone_size.x, station.Definition.TYPES.counter.width * 1.2), "training zone width should be 1.2x")
	assert(is_equal_approx(zone_size.y, 5.2 * 1.2), "training zone depth should be 1.2x")
	assert(station.model.BOUNDS == Vector2(3.35, 2.65), "counter object movement bounds should remain unchanged")
	var shelf = station.view.get_node("ProductShelf")
	assert(is_equal_approx(shelf.rotation.y, PI / 4.0), "visible product shelf should use the 45 degree rotation")
	for index in range(game.service.stations.size() - 1):
		var left = game.service.stations[index]
		var right = game.service.stations[index + 1]
		var left_edge: float = left.position.x + left.training_zone_max().x
		var right_edge: float = right.position.x + right.training_zone_min().x
		assert(absf(left_edge - right_edge) < 0.0001, "adjacent station zones should touch without overlap")
	print("PASS: movable plates, tray wine, grades, snapshot and scene")
	game._shutdown_tree(game)
	game.free()
	await process_frame
	quit()
