extends SceneTree
const Scene = preload("res://scenes/cafe.tscn")
const M = preload("res://scripts/cooking_model.gd")
var failed := false
func _initialize() -> void: run.call_deferred()
func check(ok: bool, message: String) -> void:
	if not ok:
		failed = true
		printerr("FAIL: ", message)
func run() -> void:
	print("[1/3] Full-kit wine/rag interaction and predictable controls")
	var model := M.new()
	model.reset("potato")
	model.pick_up("jug")
	check(model.held == "jug", "Other recipe's jug is usable")
	model.move_item("jug", Vector2(-999, 999))
	check(model.jug == Vector2(-M.BOUNDS.x, M.BOUNDS.y), "Outside-table movement clamps to edge")
	model.lift_held(100)
	check(model.elevations.jug <= 1.1, "Maximum item height")
	model.put_down()
	model.pick_up("rag")
	model.soaked = 225
	model.move_item("rag", model.cup)
	model.lift_held(0.6)
	for i in range(180): model.step(1.0 / 60, true, false, true)
	check(model.filled >= 224.99, "RMB squeezing still fills glass")
	print("[2/3] Tomato trajectory, customer reaction and exact replay")
	model.reset("wine")
	model.pick_up("tomato")
	model.move_item("tomato", Vector2(0, -0.8))
	model.elevations.tomato = 0.5
	model.throw_direction = Vector3(0, 0.05, -1)
	for i in range(25): model.step(1.0 / 60, true, false, true)
	check(model.tomato_hit and model.customer_reaction > 0, "Thrown tomato reaches receiver")
	var saved := model.snapshot()
	var replay := M.new()
	replay.restore(bytes_to_var(var_to_bytes(saved)))
	check(replay.snapshot() == saved, "Prank is included in food recording")
	print("[3/3] FPS at the real station, protected zones and menu role assignment")
	var game = Scene.instantiate()
	root.add_child(game)
	await process_frame
	game.set_physics_process(false)
	var station = game.service.by_id(4)
	game.service.request_training(station, "meal", 1)
	game.menu.show_station(station)
	check(game.menu.assignments.size() == 2 and game.menu.assignments[0].get_selected_id() == 1, "Default is one live role, next role unassigned")
	station.training.start_pass([0, 1])
	game.bind_training()
	check(game.player.station == station and game.player.zone_min.x == 0, "Right role is physically constrained to its zone")
	station.refresh(1, 0.016)
	check(station.zone_panels[0].visible and not station.zone_panels[1].visible, "Inactive zone visibly red")
	check(station.walls[0].visible, "Training perimeter visible")
	station.training.close()
	game.bind_training()
	check(not game.player.constrained, "Leaving lesson restores free movement")
	game.free()
	print("PASS: item input, prank replay and FPS zones" if not failed else "FAILED")
	quit(1 if failed else 0)
