extends SceneTree
const Model = preload("res://scripts/cooking_model.gd")
func _initialize() -> void: run.call_deferred()
func run() -> void:
	var m = Model.new()
	m.reset("sausage")
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2.ZERO)
	m.put_down()
	m.pick_up("sausage_0")
	m.move_item("sausage", Vector2.ZERO)
	m.put_down()
	assert(m.sausage_state == "plate_2", "food should attach to moved plate")
	m.pick_up("plate_2")
	m.move_item("plate_2", m.Layout.TRAY)
	m.put_down()
	assert(m.served_index("sausage") == 0)
	assert(m.served_in_dish("sausage"))
	var copy = Model.new()
	copy.restore(m.snapshot())
	assert(copy.served_in_dish("sausage"))
	m.reset("wine")
	m._deliver(m.Layout.TRAY, 225, 2.0)
	assert(m.served_wine() == 225)
	assert(m.quality().grade == "A")
	assert(m.spilled() == 0)
	m.reset("wine")
	m.pick_up("cup")
	m.move_item("cup", m.Layout.TRAY)
	m.put_down()
	m.filled = 225
	assert(m.quality().grade == "S")
	m._deliver(m.cup, 100, 2.0)
	assert(m.filled == 300 and m.tray_wine == 25)
	assert(m.spilled() == 0, "cup overflow on tray is served, not lost")
	m.reset("sausage")
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2.ZERO)
	m.put_down()
	m.pick_up("sausage_0")
	m.move_item("sausage", Vector2(0.1, 0.0))
	m.put_down()
	m.pick_up("plate_2")
	m.move_item("plate_2", Vector2(0.5, 0.0))
	m.lift_held(0.2)
	m.step(0.1, false, true, false)
	assert(m.sausage.distance_to(Vector2(0.6, 0)) < 0.001)
	assert(m.sausage_slip == 0)
	for i in range(10): m.step(0.1, true, false, false)
	assert(not m.sausage_state.begins_with("plate_"), "tilting plate releases food")
	var game = load("res://scenes/cafe.tscn").instantiate()
	root.add_child(game)
	await process_frame
	game.service.open_for_business = false
	for i in range(5): await process_frame
	print("PASS: movable plates, tray wine, grades, snapshot and scene")
	game._shutdown_tree(game)
	game.free()
	await process_frame
	quit()
