extends SceneTree
var failed := false
func _initialize() -> void: run.call_deferred()
func check(ok: bool, message: String) -> void:
	if not ok: failed = true; printerr("FAIL: ",message)
func run() -> void:
	var game = preload("res://scenes/cafe.tscn").instantiate()
	root.add_child(game)
	await process_frame
	game.set_physics_process(false)
	game.cookbook.toggle()
	check(game.cookbook.recipe == "index" and game.cookbook.physical.visible, "Free reading opens physical book and index")
	check(game.cookbook.overlay.visible, "Reading covers the screen so clicks stay in the book")
	game.cookbook.select("wine")
	check(game.session.capture_player().presentation.page == "wine", "Reading page enters network presence")
	game.cookbook.close()
	var station = game.service.by_id(1)
	game.service.request_training(station,"potato",1)
	station.training.start_pass([1])
	game.bind_training()
	game.menu.close()
	game.cookbook.toggle()
	check(game.cookbook.recipe == "potato", "Lesson opens current recipe")
	station.training.inputs[0] = game.build_motion(station,1.0/60)
	station.training.advance(1.0/60)
	var frame: Dictionary = station.training.pending_tracks[0].frames[0]
	check(frame.presentation.book and frame.presentation.page == "potato", "Book recorded with cooking")
	var replay = preload("res://scripts/cooking_model.gd").new()
	replay.restore(frame)
	check(replay.presentation.book,"Book restored for clone")
	var old := frame.duplicate(true)
	old.erase("presentation")
	replay.restore(old)
	check(not replay.presentation.book,"Old recording remains valid")
	check(game.service.matches_schema(old, frame), "Save schema accepts frames without presentation")
	game.cookbook.close()
	game.player.global_position = station.global_position + Vector3(0,0,1.8)
	var enter := InputEventKey.new()
	enter.pressed = true
	enter.physical_keycode = KEY_ENTER
	game._unhandled_input(enter)
	check(station.training.phase == "recording", "Enter has no finish action")
	game.session.request_action({"action":"ring","station":1})
	check(station.training.phase == "confirm_finish", "Bell asks before missing serving")
	check(station.training.pending_tracks[0].frames.back().presentation.bell == 1,"Bell stored at the ring")
	station.training.finish_pass(true)
	check(station.training.pending_tracks[0].frames.back().presentation.bell == 1,"Bell stored in final frame")
	var malformed := {"position":[0,0,0],"yaw":0.0,"pitch":0.0,"presentation":42}
	check(not game.session.clean_pose(malformed).presentation.book,"Malformed appearance safely ignored")
	game.cookbook.toggle()
	check(game.cookbook.opened, "Book can open after a take")
	game.menu.show_station(station)
	game._physics_process(1.0/60)
	check(not game.cookbook.opened, "Station menu closes the book")
	var hidden := preload("res://scripts/cook_avatar.gd").new()
	game.add_child(hidden)
	await process_frame
	hidden.hide()
	hidden.book.set_reading(true, "wine")
	check(not hidden.book.shown() and not hidden.book.page_sound.playing, "Hidden avatar does not play page turns")
	hidden.queue_free()
	game.cookbook.toggle()
	game.session.leave("test")
	check(not game.cookbook.opened, "Disconnect hides the book")
	var kitchen = game.service.by_id(4)
	game.service.request_training(kitchen, "meal", 1)
	kitchen.training.start_pass([1, 0])
	game.bind_training()
	game.menu.close()
	game.feedback.update(0)
	kitchen.model.meat_sides = [1.0, 0.0]
	game.feedback.update(0)
	check(game.feedback.latches[kitchen.station_id].sides == 1, "Steak-side ready uses the cooked-face threshold once")
	kitchen.model.meat_sides = [0.999, 0.2]
	game.feedback.update(0)
	check(game.feedback.latches[kitchen.station_id].sides == 1, "Near-threshold steak sides do not chime again")
	kitchen.training.close()
	var wine_station = game.service.by_id(2)
	game.service.request_training(wine_station, "wine", 1)
	wine_station.training.start_pass([1])
	game.bind_training()
	game.menu.close()
	game.feedback.update(0)
	wine_station.model.filled = 220
	game.feedback.update(0)
	check(game.feedback.latches[2].wine, "Wine ready matches the 200–250 ml requirement")
	wine_station.model.filled = 205
	game.feedback.update(0)
	wine_station.model.filled = 245
	game.feedback.update(0)
	check(game.feedback.latches[2].wine, "Threshold chatter does not clear the wine latch")
	wine_station.model.filled = 180
	game.feedback.update(0)
	check(not game.feedback.latches[2].wine, "Leaving the wine window allows a later announcement")
	game.queue_free()
	await process_frame
	print("PASS: cookbook, recording compatibility, presence and bell" if not failed else "FAILED")
	quit(1 if failed else 0)
